# Generated by Django 5.2.6 on 2025-09-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.IntegerField(blank=True, choices=[(1, 'Produtivo'), (2, 'Improdutivo')], null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Alta prioridade'), (2, 'Média prioridade'), (3, 'Baixa prioridade'), (0, 'N/A')], null=True)),
                ('original_text', models.TextField()),
                ('ia_suggestion_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
