# Generated by Django 5.2.6 on 2025-09-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaemail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclassification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
